[workspace]
members = [
    "src/a11y",
    "src/core",
    "src/core_internals",
    "src/crypto",
    "src/gaming",
    "src/graphics",
    "src/math",
    "src/media",
    "src/security",
]